### ISSUE TITLE
Не соответсвует правде ответ примера Example::getActualVersion

### ISSUE THREAD

**Issue by proggga** [tracker-my-com/s2s-api#1]
https://github.com/tracker-my-com/s2s-api/blob/825dd3b2da0bb1ff08d44129a838ce6c9c1eaab7/src/Example.php#L23

![image](https://user-images.githubusercontent.com/12262156/84775085-6b41c500-afe7-11ea-95b2-117d84eeadf3.png)

в примере делается каст к int
![image](https://user-images.githubusercontent.com/12262156/84774924-2c137400-afe7-11ea-8eab-924506369411.png)

а там вообще-то json
![image](https://user-images.githubusercontent.com/12262156/84774944-32a1eb80-afe7-11ea-81ff-ab0e2a0238dc.png)

**Comment by ilyas-pro** [comment]
fixed
